import os
import unittest
import rio_de_janeiro

_SOURCE_ID = "placeholder_ID"
_SOURCE_URL = "placeholder_URL"


class RioDeJaneiroTest(unittest.TestCase):
    def setUp(self):
        # Default of 1500 is not enough to show diffs when there is one.
        self.maxDiff = 10000

    def test_parse(self):
        current_dir = os.path.dirname(__file__)
        sample_data_file = os.path.join(current_dir, "sample_data.csv")

        result = rio_de_janeiro.parse_cases(sample_data_file, _SOURCE_ID, _SOURCE_URL)
        self.assertCountEqual(list(result), [{'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '05/05/2020Z', 'end': '05/05/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '05/05/2020Z', 'end': '05/05/2020Z'}}],
                                              'location': {'query': 'NOVA IGUACU                                       , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 46.0, 'end': 46.0},
                                                               'gender': 'Female'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Number of epidemiological days = 212.0\nDate case was reported was 05/05/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '05/03/2020Z', 'end': '05/03/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '05/03/2020Z', 'end': '05/03/2020Z'}}],
                                              'location': {'query': 'MACAE                                             , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 23.0, 'end': 23.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as PARQUE AEROPORTO                                                                                    \nNumber of epidemiological days = 214.0\nDate case was reported was 05/06/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '05/01/2020Z', 'end': '05/01/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '05/01/2020Z', 'end': '05/01/2020Z'}}],
                                              'location': {'query': 'MACAE                                             , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 23.0, 'end': 23.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as AJUDA DE BAIXO                                                                                      \nNumber of epidemiological days = 216.0\nDate case was reported was 05/03/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '05/23/2020Z', 'end': '05/23/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '05/23/2020Z', 'end': '05/23/2020Z'}}],
                                              'location': {'query': 'ANGRA DOS REIS                                    , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 55.0, 'end': 55.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as CENTRO                                                                                              \nNumber of epidemiological days = 194.0\nDate case was reported was 05/23/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '10/04/2020Z', 'end': '10/04/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '10/04/2020Z', 'end': '10/04/2020Z'}}],
                                              'location': {'query': 'MESQUITA                                          , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 53.0, 'end': 53.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as COREIA                                                                                              \nNumber of epidemiological days = 60.0\nDate case was reported was 10/13/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '08/07/2020Z', 'end': '08/07/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '08/07/2020Z', 'end': '08/07/2020Z'}}],
                                              'location': {'query': 'MARICA                                            , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 47.0, 'end': 47.0},
                                                               'gender': 'Female'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as GUARATIBA                                                                                           \nNumber of epidemiological days = 118.0\nDate case was reported was 08/20/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '09/07/2020Z', 'end': '09/07/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '09/07/2020Z', 'end': '09/07/2020Z'}}],
                                              'location': {'query': 'SAO JOAO DE MERITI                                , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 25.0, 'end': 25.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as EDEN                                                                                                \nNumber of epidemiological days = 87.0\nDate case was reported was 09/17/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '06/03/2020Z', 'end': '06/03/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '06/03/2020Z', 'end': '06/03/2020Z'}}],
                                              'location': {'query': 'DUQUE DE CAXIAS                                   , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 57.0, 'end': 57.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as PARQUE VITORIA                                                                                      \nNumber of epidemiological days = 183.0\nDate case was reported was 06/04/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '07/03/2020Z', 'end': '07/03/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '07/03/2020Z', 'end': '07/03/2020Z'}}],
                                              'location': {'query': 'MACAE                                             , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 33.0, 'end': 33.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as AEROPORTO                                                                                           \nNumber of epidemiological days = 153.0\nDate case was reported was 07/03/2020'},
                                             {'caseReference': {'sourceId': 'placeholder_ID',
                                                                'sourceUrl': 'placeholder_URL'},
                                              'events': [{'name': 'confirmed',
                                                          'dateRange': {'start': '07/20/2020Z', 'end': '07/20/2020Z'}},
                                                         {'name': 'onsetSymptoms',
                                                          'dateRange': {'start': '07/20/2020Z', 'end': '07/20/2020Z'}}],
                                              'location': {'query': 'ITATIAIA                                          , Rio de Janeiro, Brazil'},
                                              'demographics': {'ageRange': {'start': 50.0, 'end': 50.0}, 'gender': 'Male'},
                                              'symptoms': {'status': 'Asymptomatic'},
                                              'notes': 'Neighborhood of case is listed as CAMPO ALEGRE                                                                                        \nNumber of epidemiological days = 136.0\nDate case was reported was 07/20/2020'}])
