@startditaa

+-------------+
| Upstream    |case data  +---------------+     +------------+     +------------+
| data source +---------->+ ADI Retrieval +---->+ S3 {s}     +---->+ ADI Parser |
| {d}         |           +---------------+     +------------+     +------+-----+
+-------------+                                    case data (normalised) |
                                              +---------------------------+
                                              |
                                              v
+------------+      +------------+     +------+------+  case data   +----------+
|Browser {io}+<---->+ Curator UI +<--->+ Curator API +<------------>+ Data API +<---------+
+-----+------+      +------------+     +---+---+-----+              +------+---+          |
      |                                    ^   ^                           ^              |
      |                                    |   | ADI sources               | case data    | geocoding
 +----+-----+                              |   | user records              v              | queries and results
 | Google   |                              |   |                      +----+--------+     |
 | Auth {io}|                              |   +--------------------->+ mongo DB {s}|     |
 +----------+                              |                          +------+------+     |
                                           |                                 |            |
                                           |           cached admin regions  v            |
                                           |                          +------+-------+    |
                                           +------------------------->+ Location API +<---+
                                             geocoding Qs and As      +------+-------+
                                                                             |
                                                                       +-----+------+
                                                                       | Mapbox {o} |
                                                                       +------------+
@endditaa