openapi: 3.0.3
info:
  title: EPID data service
  description: Server for CRUD operations on EPID line-list data
  termsOfService: "https://www.healthmap.org/about/termsofuse/"
  contact:
    email: info@healthmap.org
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
  version: 1.0.0
paths:
  /cases/{id}:
    parameters:
      - name: id
        in: path
        description: The case ID
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Gets a specific case
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Case"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "422":
          $ref: "#/components/responses/422"
components:
  schemas:
    Case:
      type: object
  responses:
    "400":
      description: Malformed request
    "401":
      description: Unauthorized
    "404":
      description: Not found
    "422":
      description: Unprocessable entity
servers:
  - url: "http://localhost:3000/api"
    description: Local server
