openapi: 3.0.3
info:
  title: Global Health data service
  description: Server for CRUD operations on Global Health line-list data
  termsOfService: "https://www.healthmap.org/about/termsofuse/"
  contact:
    email: info@healthmap.org
  license:
    name: MIT
    url: "https://opensource.org/licenses/MIT"
  version: 1.0.0
paths:
  /cases:
    get:
      summary: Lists cases
      operationId: listCases
      parameters:
        - name: page
          in: query
          description: The pages of cases to skip before starting to collect the result set
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: The number of items to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 10
        - name: q
          in: query
          description: The search query
          required: false
          schema:
            type: string
      responses:
        "200":
          $ref: "#/components/responses/200CaseArray"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "422":
          $ref: "#/components/responses/422"
        "500":
          $ref: "#/components/responses/500"
    post:
      summary: Creates a new case
      operationId: createCase
      requestBody:
        description: Case to add
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewCase"
      parameters:
        - name: validate_only
          in: query
          description: Whether to validate the case without creating it
          required: false
          schema:
            type: boolean
            default: false
          allowEmptyValue: true
      responses:
        "201":
          $ref: "#/components/responses/201Case"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "422":
          $ref: "#/components/responses/422"
        "500":
          $ref: "#/components/responses/500"
    put:
      summary: Upserts a case
      description: >
        Creates or updates a case, depending on whether the provided values for
        the `caseReference.sourceId` and `caseReference.sourceEntryId` fields
        correspond to an existing case record.
      operationId: upsertCase
      requestBody:
        description: Case to upsert
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/Case"
              required:
                - caseReference
      responses:
        "200":
          $ref: "#/components/responses/200Case"
        "201":
          $ref: "#/components/responses/201Case"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "422":
          $ref: "#/components/responses/422"
        "500":
          $ref: "#/components/responses/500"
  /cases/batchValidate:
    post:
      summary: Batch validates cases
      operationId: batchValidateCases
      requestBody:
        description: Cases to validate
        required: true
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/CaseArray"
      responses:
        "207":
          $ref: "#/components/responses/207BatchValidateCaseResponse"
        "500":
          $ref: "#/components/responses/500"
  /cases/{id}:
    parameters:
      - name: id
        in: path
        description: The case ID
        required: true
        schema:
          type: string
          pattern: '^[a-f\d]{24}$'
    get:
      summary: Gets a specific case
      operationId: getCase
      responses:
        "200":
          $ref: "#/components/responses/200Case"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "422":
          $ref: "#/components/responses/422"
        "500":
          $ref: "#/components/responses/500"
    put:
      summary: Updates a specific case
      operationId: updateCase
      requestBody:
        description: Case to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Case"
      responses:
        "200":
          $ref: "#/components/responses/200Case"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "422":
          $ref: "#/components/responses/422"
        "500":
          $ref: "#/components/responses/500"
    delete:
      summary: Deletes a specific case
      operationId: deleteCase
      responses:
        "204":
          description: Case deleted
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    BatchValidateCaseResponse:
      description: Response to batch validate case API requests
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
              message:
                type: string
            required:
              - index
              - message
      required:
        - errors
    Case:
      description: A single line-list case.
      properties:
        caseReference:
          type: object
          properties:
            sourceId:
              type: string
              pattern: '^[a-f\d]{24}$'
            sourceUrl:
              type: string
            additionalSources:
              type: array
              items:
                type: object
                properties:
                  sourceUrl:
                    type: string
        demographics:
          type: object
          properties:
            gender:
              type: string
            ageRange:
              type: object
              properties:
                start:
                  type: number
                end:
                  type: number
            ethnicity:
              type: string
            nationalities:
              type: array
              items:
                type: string
            occupation:
              type: string
        location:
          type: object
          properties:
            country:
              type: string
            administrativeAreaLevel1:
              type: string
            administrativeAreaLevel2:
              type: string
            administrativeAreaLevel3:
              type: string
            place:
              type: string
            name:
              type: string
            geoResolution: 
              type: string
            geometry:
              type: object
              properties:
                latitude:
                  type: number
                longitude:
                  type: number
              required:
                - latitude
                - longitude
        events:
          description: > 
            An event with name "confirmed" must be specified. Other event names
            include onsetSymptoms, firstClinicalConsultation, selfIsolation,
            hospitalAdmission, icuAdmission, and outcome.
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              dateRange:
                type: object
                properties:
                  start:
                    oneOf:
                      - type: string
                      - type: object
                      - type: number
                  end:
                    oneOf:
                      - type: string
                      - type: object
                      - type: number
              value:
                type: string
        symptoms:
          type: object
          properties:
            status:
              type: string
            values:
              type: array
              items:
                type: string
        preexistingConditions:
          type: object
          properties:
            hasPreexistingConditions:
              type: boolean
            values:
              type: array
              items:
                type: string
        transmission:
          type: object
          properties:
            routes:
              type: array
              items:
                type: string
            places:
              type: array
              items:
                type: string
            linkedCaseIds:
              type: array
              items:
                type: string
        travelHistory:
          type: object
        genomeSequences:
          type: array
          items:
            type: object
        pathogens:
          type: array
          items:
            type: object
        notes:
          type: string
        revisionMetadata:
          type: object
    CaseArray:
      type: object
      properties:
        cases:
          type: array
          items:
            $ref: "#/components/schemas/Case"
      required:
        - cases
    NewCase:
      description: A "#/components/schemas/Case" with additional required fields for newly-created cases
      allOf:
        - $ref: "#/components/schemas/Case"
      properties:
        caseReference:
          required:
            - sourceId
            - sourceUrl
        location:
          required:
            - country
            - geoResolution
            - geometry
            - name
      required:
        - caseReference
        - location
        - events
        - revisionMetadata
  responses:
    "200Case":
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Case"
    "200CaseArray":
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CaseArray"
    "201Case":
      description: Created
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Case"
    "207BatchValidateCaseResponse":
      description: Multi-status
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BatchValidateCaseResponse'
    "400":
      description: Malformed request
    "403":
      description: Forbidden
    "404":
      description: Not found
    "422":
      description: Unprocessable entity
    "500":
      description: Internal server error
servers:
  - url: http://localhost:3000/api
    description: Local server