import os
import unittest
import england

_SOURCE_ID = "placeholder_ID"
_SOURCE_URL = "placeholder_URL"


class EnglandTest(unittest.TestCase):
    def setUp(self):
        self.maxDiff = 5000

    def test_parse(self):
        '''
        Includes a row where province and district are unspecified, where it should return just
        the department and country
        '''
        current_dir = os.path.dirname(__file__)
        sample_data_file = os.path.join(current_dir, "sample_data.csv")

        result = england.parse_cases(sample_data_file, _SOURCE_ID, _SOURCE_URL)
        self.assertCountEqual(list(result),
                              [{'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '2877343',
                                                  'sourceUrl': 'placeholder_URL'},
                                'location': {'country': 'United Kingdom',
                                             'geoResolution': 'Admin3',
                                             'name': 'Bristol, City of, Bristol, City of, United Kingdom',
                                             'geometry': {'latitude': 51.47115, 'longitude': -2.57742},
                                             'administrativeAreaLevel1': 'South West',
                                             'administrativeAreaLevel2': 'Bristol, City of',
                                             'administrativeAreaLevel3': 'Bristol, City of'},
                                  'demographics': {'ageRange': {'start': 24.0, 'end': 24.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                'events': [{'name': 'confirmed',
                                            'value': 'PCR test',
                                            'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                'symptoms': {'status': 'Asymptomatic'},
                                'notes': 'Case was in an area with an Index of Multiple Deprivation = 9.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '1819443',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Cheltenham, Gloucestershire, United Kingdom',
                                               'geometry': {'latitude': 51.89861, 'longitude': -2.07515},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Gloucestershire',
                                               'administrativeAreaLevel3': 'Cheltenham'},
                                  'demographics': {'ageRange': {'start': 35.0, 'end': 35.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                'events': [{'name': 'confirmed',
                                            'value': 'PCR test',
                                            'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Symptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 2.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '2271302',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Bristol, City of, Bristol, City of, United Kingdom',
                                               'geometry': {'latitude': 51.47115, 'longitude': -2.57742},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Bristol, City of',
                                               'administrativeAreaLevel3': 'Bristol, City of'},
                                  'demographics': {'ageRange': {'start': 30.0, 'end': 30.0},
                                                   'gender': 'Male',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Symptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 1.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '384704',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Plymouth, Plymouth, United Kingdom',
                                               'geometry': {'latitude': 50.40494, 'longitude': -4.11297},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Plymouth',
                                               'administrativeAreaLevel3': 'Plymouth'},
                                  'demographics': {'ageRange': {'start': 49.0, 'end': 49.0},
                                                   'gender': 'Male',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Asymptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 4.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '1342437',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'South Somerset, Somerset, United Kingdom',
                                               'geometry': {'latitude': 50.98399, 'longitude': -2.77588},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Somerset',
                                               'administrativeAreaLevel3': 'South Somerset'},
                                  'demographics': {'ageRange': {'start': 42.0, 'end': 42.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Asymptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 5.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '1841863',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'South Gloucestershire, South Gloucestershire, United Kingdom',
                                               'geometry': {'latitude': 51.54673, 'longitude': -2.46922},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'South Gloucestershire',
                                               'administrativeAreaLevel3': 'South Gloucestershire'},
                                  'demographics': {'ageRange': {'start': 55.0, 'end': 55.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Asymptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 9.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '2576349',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Mendip, Somerset, United Kingdom',
                                               'geometry': {'latitude': 51.19476, 'longitude': -2.54178},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Somerset',
                                               'administrativeAreaLevel3': 'Mendip'},
                                  'demographics': {'ageRange': {'start': 35.0, 'end': 35.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Symptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 7.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '2429985',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Wiltshire, Wiltshire, United Kingdom',
                                               'geometry': {'latitude': 51.32883, 'longitude': -1.92661},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Wiltshire',
                                               'administrativeAreaLevel3': 'Wiltshire'},
                                  'demographics': {'ageRange': {'start': 58.0, 'end': 58.0},
                                                   'gender': 'Male',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Asymptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 7.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '597503',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Cheltenham, Gloucestershire, United Kingdom',
                                               'geometry': {'latitude': 51.89861, 'longitude': -2.07515},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Gloucestershire',
                                               'administrativeAreaLevel3': 'Cheltenham'},
                                  'demographics': {'ageRange': {'start': 6.0, 'end': 6.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Symptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 10.0.'},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '238701',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'country': 'United Kingdom',
                                               'geoResolution': 'Admin3',
                                               'name': 'Swindon, Swindon, United Kingdom',
                                               'geometry': {'latitude': 51.57763, 'longitude': -1.73367},
                                               'administrativeAreaLevel1': 'South West',
                                               'administrativeAreaLevel2': 'Swindon',
                                               'administrativeAreaLevel3': 'Swindon'},
                                  'demographics': {'ageRange': {'start': 52.0, 'end': 52.0},
                                                   'gender': 'Female',
                                                   'ethnicity': 'White'},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '02/24/2021Z', 'end': '02/24/2021Z'}}],
                                  'symptoms': {'status': 'Asymptomatic'},
                                  'notes': 'Case was in an area with an Index of Multiple Deprivation = 5.0.'}])
