version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "epid-ingestion"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1txyh416iht6x"
s3_prefix = "epid-ingestion"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
