AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda functions for epid ingestion

Resources:
  RawSourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: epid-sources-raw
  RetrievalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: retrieval/
      Handler: retrieval.lambda_handler
      Runtime: python3.6
      Description: Retrieve the executing machine IP
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - S3WritePolicy:
            BucketName: !Ref RawSourcesBucket
      Timeout: 10 # Seconds

# Declare values that can be imported to other CloudFormation stacks, or should
# be made easily visible on the console.
# For more information:
#   https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  RetrievalFunction:
    Description: "Retrieval Lambda function ARN"
    Value: !GetAtt RetrievalFunction.Arn
