AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda functions for Global Health ingestion

Globals:
  Function:
    Runtime: python3.8
    Timeout: 900
    Layers:
      - !Ref CommonLibLayer

Resources:
  RawSourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: epid-sources-raw
  RetrievalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: retrieval/
      Handler: retrieval.lambda_handler
      Description: Retrieve raw source content
      # Function's execution role
      Policies:
        - AWSLambdaFullAccess
        - S3WritePolicy:
            BucketName: !Ref RawSourcesBucket
  ParsingLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: parsing_lib
      Description: Common functions required for parsing
      ContentUri: parsing/common/python/parsing_lib
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
  CommonLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_lib
      Description: Common functions between parsing and retrieval
      ContentUri: common
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
  IndiaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/india/
      Handler: india.lambda_handler
      Description: Parse case data for India
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  HongKongParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/hongkong/
      Handler: hongkong.lambda_handler
      Description: Parse case data for HongKong
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  JapanParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/japan/
      Handler: japan.lambda_handler
      Description: Parse case data for Japan
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 512
      Layers:
        - !Ref ParsingLibLayer
  CHZurichParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/ch_zurich/
      Handler: zurich.lambda_handler
      Description: Parse case data for the Zurich Canton of Switzerland
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilParaibaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_paraiba/
      Handler: paraiba.lambda_handler
      Description: Parse case data for the Paraiba State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
# Declare values that can be imported to other CloudFormation stacks, or should
# be made easily visible on the console.
# For more information:
#   https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  RetrievalFunction:
    Description: "Retrieval Lambda function ARN"
    Value: !GetAtt RetrievalFunction.Arn
