AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda functions for Global Health ingestion

Globals:
  Function:
    Runtime: python3.8
    Timeout: 900
    EventInvokeConfig:
      MaximumRetryAttempts: 0
    Layers:
      - !Ref CommonLibLayer

Resources:
  RawSourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: epid-sources-raw
  RetrievalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: retrieval/
      Handler: retrieval.lambda_handler
      Description: Retrieve raw source content
      MemorySize: 1024
      # Function's execution role
      Policies:
        - AWSLambdaFullAccess
        - S3WritePolicy:
            BucketName: !Ref RawSourcesBucket
  ParsingLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: parsing_lib
      Description: Common functions required for parsing
      ContentUri: parsing/common/python/parsing_lib
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
  CommonLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: common_lib
      Description: Common functions between parsing and retrieval
      ContentUri: common
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
  ThailandParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/thailand/
      Handler: thailand.lambda_handler
      Description: Parse case data for Thailand
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  IndiaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/india/
      Handler: india.lambda_handler
      Description: Parse case data for India
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  HongKongParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/hongkong/
      Handler: hongkong.lambda_handler
      Description: Parse case data for HongKong
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  ExampleParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/example/
      Handler: example.lambda_handler
      Description: Example parser
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 512
      Layers:
        - !Ref ParsingLibLayer
  JapanParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/japan/
      Handler: japan.lambda_handler
      Description: Parse case data for Japan
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 512
      Layers:
        - !Ref ParsingLibLayer
  EstoniaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/estonia/
      Handler: estonia.lambda_handler
      Description: Parse case data for Estonia
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 512
      Layers:
        - !Ref ParsingLibLayer
  CHZurichParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/ch_zurich/
      Handler: zurich.lambda_handler
      Description: Parse case data for the Zurich Canton of Switzerland
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  GermanyParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/germany/
      Handler: germany.lambda_handler
      Description: Parse case data for Germany
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  PeruParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/peru/
      Handler: peru.lambda_handler
      Description: Parse case data across Peru
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 1024
      Layers:
        - !Ref ParsingLibLayer
  BrazilAmapaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_amapa/
      Handler: amapa.lambda_handler
      Description: Parse case data for the Amapa State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilParaibaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_paraiba/
      Handler: paraiba.lambda_handler
      Description: Parse case data for the Paraiba State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilRGDSParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/riograndedosul/
      Handler: riograndedosul.lambda_handler
      Description: Parse case data for the Rio Grande do Sul State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  ColombiaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/colombia/
      Handler: colombia.lambda_handler
      Description: Parse case data for Colombia
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 1024
      Layers:
        - !Ref ParsingLibLayer
  TaiwanParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/taiwan/
      Handler: taiwan.lambda_handler
      Description: Parse case data for Taiwan
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  MexicoParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/mexico/
      Handler: mexico.lambda_handler
      Description: Parse case data for Mexico
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 1024
      Layers:
        - !Ref ParsingLibLayer
  ArgentinaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/argentina/
      Handler: argentina.lambda_handler
      Description: Parse case data for Argentina
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      MemorySize: 1024
      Layers:
        - !Ref ParsingLibLayer
  CubaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/cuba/
      Handler: cuba.lambda_handler
      Description: Parse case data for Cuba
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  SaoPaoloParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/saopaolo/
      Handler: saopaolo.lambda_handler
      Description: Parse case data for the Sao Paolo State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilDistritoFederalParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_distrito_federal/
      Handler: distrito_federal.lambda_handler
      Description: Parse case data for the Distrito Federal State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilAcreParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_acre/
      Handler: acre.lambda_handler
      Description: Parse case data for the Acre State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilEspiritoSantoParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_espirito_santo/
      Handler: espirito_santo.lambda_handler
      Description: Parse case data for the Espirito Santo State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilGoiasParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_goias/
      Handler: goias.lambda_handler
      Description: Parse case data for the Goias State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
  BrazilParaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/brazil_para/
      Handler: para.lambda_handler
      Description: Parse case data for the Para State of Brazil
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Layers:
        - !Ref ParsingLibLayer
      
# Declare values that can be imported to other CloudFormation stacks, or should
# be made easily visible on the console.
# For more information:
#   https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  RetrievalFunction:
    Description: "Retrieval Lambda function ARN"
    Value: !GetAtt RetrievalFunction.Arn

