AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda functions for Global Health ingestion

Parameters:
  SourceApiUrl:
    Type: String
    Description: Address at which to retrieve source details
    Default: "http://localhost:3001/api"

Resources:
  RawSourcesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: epid-sources-raw
  RetrievalFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: retrieval/
      Handler: retrieval.lambda_handler
      Runtime: python3.8
      Description: Retrieve raw source content
      # Function's execution role
      Policies:
        - AWSLambdaFullAccess
        - S3WritePolicy:
            BucketName: !Ref RawSourcesBucket
      Timeout: 60 # Seconds
      Environment:
        Variables:
          SOURCE_API_URL:
            Ref: SourceApiUrl
          # Workaround for a bug with the existing SAM CLI 1.0 Docker images.
          # Re: https://github.com/awslabs/aws-sam-cli/issues/2135
          AWS_SESSION_TOKEN: ""
  ParsingLibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: parsing_lib
      Description: Common functions required for parsing
      ContentUri: parsing/common/python/parsing_lib
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8
  IndiaParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/india/
      Handler: india.lambda_handler
      Runtime: python3.8
      Description: Parse case data for India
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Timeout: 60 # Seconds
      Layers:
        - !Ref ParsingLibLayer
      Environment:
        Variables:
          SOURCE_API_URL:
            Ref: SourceApiUrl
          # Workaround for a bug with the existing SAM CLI 1.0 Docker images.
          # Re: https://github.com/awslabs/aws-sam-cli/issues/2135
          AWS_SESSION_TOKEN: ""
  HongKongParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/hongkong/
      Handler: hongkong.lambda_handler
      Runtime: python3.8
      Description: Parse case data for India
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Timeout: 60 # Seconds
      Layers:
        - !Ref ParsingLibLayer
      Environment:
        Variables:
          SOURCE_API_URL:
            Ref: SourceApiUrl
          # Workaround for a bug with the existing SAM CLI 1.0 Docker images.
          # Re: https://github.com/awslabs/aws-sam-cli/issues/2135
          AWS_SESSION_TOKEN: ""
  CHZurichParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/ch_zurich/
      Handler: zurich.lambda_handler
      Runtime: python3.8
      Description: Parse case data for the Zurich Canton of Switzerland
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Timeout: 60 # Seconds
      Layers:
        - !Ref ParsingLibLayer
      Environment:
        Variables:
          SOURCE_API_URL:
            Ref: SourceApiUrl
          # Workaround for a bug with the existing SAM CLI 1.0 Docker images.
          # Re: https://github.com/awslabs/aws-sam-cli/issues/2135
          AWS_SESSION_TOKEN: ""
  GermanyParsingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: parsing/germany/
      Handler: germany.lambda_handler
      Runtime: python3.8
      Description: Parse case data for Germany
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Timeout: 60 # Seconds
      Layers:
        - !Ref ParsingLibLayer
      Environment:
        Variables:
          SOURCE_API_URL:
            Ref: SourceApiUrl
          # Workaround for a bug with the existing SAM CLI 1.0 Docker images.
          # Re: https://github.com/awslabs/aws-sam-cli/issues/2135
          AWS_SESSION_TOKEN: ""

# Declare values that can be imported to other CloudFormation stacks, or should
# be made easily visible on the console.
# For more information:
#   https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  RetrievalFunction:
    Description: "Retrieval Lambda function ARN"
    Value: !GetAtt RetrievalFunction.Arn
