# Kubernetes deployment file for the Global Health service on AWS.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curator-dev
  labels:
    environment: dev
    app: curator
spec:
  selector:
    matchLabels:
      environment: dev
      app: curator
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
        app: curator
    spec:
      containers:
        - name: curator
          image: ghcr.io/globaldothealth/list/curatorservice:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            # TODO: Remove this pending https://github.com/globaldothealth/list/issues/961.
            # Run with node debug mode set to http, net, and tls.
            - name: NODE_DEBUG
              value: "http,net,tls"
            - name: EVENT_ROLE_ARN
              value: "arn:aws:iam::612888738066:role/service-role/AWS_Events_Invoke_Batch_Job_Queue_1312384119"
            - name: JOB_QUEUE_ARN
              value: "arn:aws:batch:us-east-1:612888738066:job-queue/ingestion-queue"
            - name: SERVICE_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['environment']
            - name: DATASERVER_URL
              value: "http://data-dev"
            - name: LOCATION_SERVICE_URL
              value: "http://location-dev"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: db_connection_string
            - name: SESSION_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: session_cookie_key
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: google_oauth_client_secret
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: google_oauth_client_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_secret_access_key
            - name: EMAIL_USER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: curator-dev-969ttc49f5
                  key: email_user_address
            - name: EMAIL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curator-dev-969ttc49f5
                  key: email_user_password
            - name: AWS_SES_REGION
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_ses_region
            - name: AWS_SES_SENDER
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_ses_sender
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curator-prod
  labels:
    environment: prod
    app: curator
spec:
  selector:
    matchLabels:
      environment: prod
      app: curator
  replicas: 2
  template:
    metadata:
      labels:
        environment: prod
        app: curator
    spec:
      containers:
        - name: curator
          image: ghcr.io/globaldothealth/list/curatorservice:1.6.2
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: EVENT_ROLE_ARN
              value: "arn:aws:iam::612888738066:role/service-role/AWS_Events_Invoke_Batch_Job_Queue_1312384119"
            - name: JOB_QUEUE_ARN
              value: "arn:aws:batch:us-east-1:612888738066:job-queue/ingestion-queue"
            - name: SERVICE_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['environment']
            - name: DATASERVER_URL
              value: "http://data-prod"
            - name: LOCATION_SERVICE_URL
              value: "http://location-prod"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: db_connection_string
            - name: SESSION_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: session_cookie_key
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: google_oauth_client_secret
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: google_oauth_client_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_secret_access_key
            - name: EMAIL_USER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: curator-prod-9gkgc49f9h
                  key: email_user_address
            - name: EMAIL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: curator-prod-9gkgc49f9h
                  key: email_user_password
            - name: AWS_SES_REGION
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_ses_region
            - name: AWS_SES_SENDER
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_ses_sender
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "768m"
---
apiVersion: v1
kind: Service
metadata:
  name: curator-dev
spec:
  selector:
    app: curator
    environment: dev
  ports:
    - port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: curator-prod
spec:
  selector:
    app: curator
    environment: prod
  ports:
    - port: 80
      targetPort: 3001
