# Kubernetes deployment file for the Global Health service on AWS.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curator-dev
  labels:
    environment: dev
    app: curator
spec:
  selector:
    matchLabels:
      environment: dev
      app: curator
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
        app: curator
    spec:
      containers:
        - name: curator
          image: docker.io/healthmapidha/curatorservice:latest
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: SERVICE_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels.environment
            - name: DATASERVER_URL
              value: "http://data-dev"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: db_connection_string
            - name: SESSION_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: session_cookie_key
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: google_oauth_client_secret
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: google_oauth_client_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: aws_secret_access_key
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: curator-dev-bch28c9gkm
                  key: mapbox_token
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curator-prod
  labels:
    environment: prod
    app: curator
spec:
  selector:
    matchLabels:
      environment: prod
      app: curator
  replicas: 1
  template:
    metadata:
      labels:
        environment: prod
        app: curator
    spec:
      containers:
        - name: curator
          image: docker.io/healthmapidha/curatorservice:0.0.11
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: DATASERVER_URL
              value: "http://data-prod"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: db_connection_string
            - name: SESSION_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: session_cookie_key
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: google_oauth_client_secret
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: google_oauth_client_id
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: aws_secret_access_key
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: curator-prod-4mtk8mh9t2
                  key: mapbox_token
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: curator-dev
spec:
  selector:
    app: curator
    environment: dev
  ports:
    - port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: curator-prod
spec:
  selector:
    app: curator
    environment: prod
  ports:
    - port: 80
      targetPort: 3001
