# Ingress defines how load balancers should forward traffic
# from the internet traffic to the cluster.
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: curator
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # TODO: switch to prod once confirmed working.
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - dev-curator.ghdsi.org
      secretName: dev-curator-ghdsi-org-cert
    - hosts:
        - curator.ghdsi.org
      secretName: curator-ghdsi-org-cert
  rules:
    - host: dev-curator.ghdsi.org
      http:
        paths:
          - backend:
              serviceName: curator-dev
              servicePort: 80
    - host: curator.ghdsi.org
      http:
        paths:
          - backend:
              serviceName: curator-prod
              servicePort: 80
