# Kubernetes deployment file for the epid service on AWS.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curator
  labels:
    environment: dev
    app: curator
spec:
  selector:
    matchLabels:
      app: curator
  replicas: 1
  template:
    metadata:
      labels:
        app: curator
    spec:
      containers:
        - name: curator
          image: docker.io/healthmapidha/curatorservice:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATASERVER_URL
              value: "http://data"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: curator-kkhd8mbt65
                  key: db_connection_string
            - name: SESSION_COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: curator-kkhd8mbt65
                  key: session_cookie_key
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: curator-kkhd8mbt65
                  key: google_oauth_client_secret
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: curator-kkhd8mbt65
                  key: google_oauth_client_id
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: curator
spec:
  selector:
    app: curator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
