version: "3"
services:
  data:
    # TODO: Move to our org repo once we have one.
    image: "docker.io/attwad/epiddata"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      # TODO: Move to aws credentials storage as better practice.
      DB_CONNECTION_STRING: "${DATASERVICE_DB_CONNECTION_STRING}"
    logging:
      driver: awslogs
      options:
        awslogs-group: epid-dev
        awslogs-region: us-east-1
        awslogs-stream-prefix: data
