import os
import unittest
from variants import variants

_SOURCE_ID = "placeholder_ID"
_SOURCE_URL = "placeholder_URL"


class VariantsTest(unittest.TestCase):
    def setUp(self):
        self.maxDiff = 5000

    def test_parse(self):
        current_dir = os.path.dirname(__file__)
        sample_data_file = os.path.join(current_dir, "sample_data.csv")

        result = variants.parse_cases(
            sample_data_file, _SOURCE_ID, _SOURCE_URL)
        self.assertCountEqual(list(result),
  [{'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.wtoc.com/2021/01/28/health-department-nations-first-cases-south-african-covid-variant-found-sc/',
   'sourceEntryId': 'voc_1'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/28/2020Z', 'end': '12/28/2020Z'}}],
  'demographics': {'ageRange': {'start': 18.0, 'end': 120.0}},
  'location': {'query': 'South Carolina, United States'},
  'travelHistory': {'traveledPrior30Days': False},
  'notes': 'Lowcountry region'},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.wtoc.com/2021/01/28/health-department-nations-first-cases-south-african-covid-variant-found-sc/',
   'sourceEntryId': 'voc_2'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/28/2020Z', 'end': '12/28/2020Z'}}],
  'demographics': {'ageRange': {'start': 18.0, 'end': 120.0}},
  'location': {'query': 'South Carolina, United States'},
  'travelHistory': {'traveledPrior30Days': False},
  'notes': 'Pee Dee region'},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.theguardian.com/world/2021/jan/27/encouraging-signs-new-zealand-hopes-for-covid-all-clear-after-no-new-cases-reported',
   'sourceEntryId': 'voc_3'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/24/2021Z', 'end': '01/27/2021Z'}}],
  'additionalSources': ['https://www.theguardian.com/world/2021/jan/24/new-zealand-records-first-covid-community-case-intwo-months'],
  'demographics': {'ageRange': {'start': 56.0, 'end': 56.0},
   'nationalities': ['New Zealander'],
   'gender': 'Female'},
  'location': {'query': 'Auckland, Auckland, New Zealand'},
  'travelHistory': {'traveledPrior30Days': True,
   'travel': [{'methods': ['Flight'],
     'location': {'query': 'London, United Kingdom'},
     'dateRange': {'start': '12/30/2020Z', 'end': '12/30/2020Z'}}]}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.theguardian.com/world/2021/jan/27/encouraging-signs-new-zealand-hopes-for-covid-all-clear-after-no-new-cases-reported',
   'sourceEntryId': 'voc_4'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/27/2021Z', 'end': '01/27/2021Z'}}],
  'location': {'query': 'Auckland, Auckland, New Zealand'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.theguardian.com/world/2021/jan/27/encouraging-signs-new-zealand-hopes-for-covid-all-clear-after-no-new-cases-reported',
   'sourceEntryId': 'voc_5'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/27/2021Z', 'end': '01/27/2021Z'}}],
  'location': {'query': 'Auckland, Auckland, New Zealand'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_6'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_7'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_8'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_9'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_10'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_11'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_12'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_13'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_14'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_15'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_16'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_17'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_18'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_19'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_20'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_21'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_22'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_23'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_24'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_25'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_26'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://twitter.com/danieljbridges/status/1344227535870164992',
   'sourceEntryId': 'voc_27'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/23/2020Z', 'end': '12/23/2020Z'}}],
  'location': {'query': 'Zambia'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.sabcnews.com/sabcnews/botswana-government-adjusts-national-lockdown-regulations/',
   'sourceEntryId': 'voc_28'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/01/2021Z', 'end': '01/07/2021Z'}}],
  'location': {'query': 'Botswana'}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.france24.com/en/france/20201231-france-detects-first-case-of-south-african-strain-of-covid-19',
   'sourceEntryId': 'voc_29'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '12/31/2020Z', 'end': '12/31/2020Z'}}],
  'location': {'query': 'Haut-Rhin, France'},
  'travelHistory': {'traveledPrior30Days': True,
   'travel': [{'methods': ['Flight'],
     'location': {'query': 'South Africa'}}]}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'http://outbreaknewstoday.com/sweden-reports-1st-south-african-covid-19-virus-variant-49394/',
   'sourceEntryId': 'voc_30'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/03/2021Z', 'end': '01/03/2021Z'}}],
  'location': {'query': 'Sweden'},
  'travelHistory': {'traveledPrior30Days': True,
   'travel': [{'location': {'query': 'South Africa'}}]}},
 {'caseReference': {'sourceId': 'placeholder_ID',
   'sourceUrl': 'https://www.vg.no/nyheter/innenriks/i/rgzer8/mer-smittsom-virusmutasjon-fra-soer-afrika-paavist-i-norge',
   'sourceEntryId': 'voc_31'},
  'events': [{'name': 'confirmed',
    'dateRange': {'start': '01/04/2021Z', 'end': '01/04/2021Z'}}],
  'location': {'query': 'Norway'},
  'travelHistory': {'traveledPrior30Days': True,
   'travel': [{'methods': ['Flight'],
     'location': {'query': 'South Africa'},
     'dateRange': {'start': '12/31/2020Z', 'end': '12/01/2020Z'}}]}}])
