/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-2',
    aws_cognito_identity_pool_id:
        'us-east-2:46365198-062a-4661-bfe8-308ab4b7015a',
    aws_cognito_region: 'us-east-2',
    aws_user_pools_id: 'us-east-2_yP0cv1Ayq',
    aws_user_pools_web_client_id: '3r3252qn4n5mi0g274p6vj2031',
    oauth: {},
};

export default awsmobile;
