import os
import unittest
from colombia import colombia


_SOURCE_ID = "place_holder_ID"
_SOURCE_URL = "place_holder_URL"


class ColombiaTest(unittest.TestCase):
    def setUp(self):
        self.maxDiff = 10000

    def test_parse(self):
        '''
        Includes imported and internally transmitted cases
        '''
        current_dir = os.path.dirname(__file__)
        sample_data_file = os.path.join(current_dir, "sample_data.csv")
        result = colombia.parse_cases(
            sample_data_file, _SOURCE_ID, _SOURCE_URL)
        self.assertCountEqual(
            list(result),
            [{'caseReference': {'sourceId': 'place_holder_ID',
                                'sourceEntryId': '1',
                                'sourceUrl': 'place_holder_URL'},
                'location': {'query': 'BOGOTA, BOGOTA, Colombia'},
              'demographics': {'ageRange': {'start': 19.0, 'end': 19.0},
                               'gender': 'Female',
                               'ethnicity': 'Other'},
              'events': [{'name': 'confirmed',
                          'dateRange': {'start': '03/06/2020Z', 'end': '03/06/2020Z'}},
                         {'name': 'onsetSymptoms',
                          'dateRange': {'start': '02/27/2020Z', 'end': '02/27/2020Z'}},
                         {'name': 'outcome',
                          'value': 'Recovered',
                          'dateRange': {'start': '03/13/2020Z', 'end': '03/13/2020Z'}}],
                'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ITALIA. \nDate reported online was 03/06/2020. \nDate reported to SIVIGILA was 03/02/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '2',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'BUGA, VALLE, Colombia'},
                 'demographics': {'ageRange': {'start': 34.0, 'end': 34.0},
                                  'gender': 'Male',
                                  'ethnicity': 'Black'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/09/2020Z', 'end': '03/09/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/04/2020Z', 'end': '03/04/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/19/2020Z', 'end': '03/19/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESPAÑA. \nDate reported online was 03/09/2020. \nDate reported to SIVIGILA was 03/06/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '3',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'MEDELLIN, ANTIOQUIA, Colombia'},
                 'demographics': {'ageRange': {'start': 50.0, 'end': 50.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/09/2020Z', 'end': '03/09/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '02/29/2020Z', 'end': '02/29/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/15/2020Z', 'end': '03/15/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESPAÑA. \nDate reported online was 03/09/2020. \nDate reported to SIVIGILA was 03/07/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '4',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'MEDELLIN, ANTIOQUIA, Colombia'},
                 'demographics': {'ageRange': {'start': 55.0, 'end': 55.0},
                                  'gender': 'Male',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/06/2020Z', 'end': '03/06/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/26/2020Z', 'end': '03/26/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase was transmitted within Colombia. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/09/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '5',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'MEDELLIN, ANTIOQUIA, Colombia'},
                 'demographics': {'ageRange': {'start': 25.0, 'end': 25.0},
                                  'gender': 'Male',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/08/2020Z', 'end': '03/08/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/23/2020Z', 'end': '03/23/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase was transmitted within Colombia. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/09/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '6',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'ITAGUI, ANTIOQUIA, Colombia'},
                 'demographics': {'ageRange': {'start': 27.0, 'end': 27.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/06/2020Z', 'end': '03/06/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/26/2020Z', 'end': '03/26/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase was transmitted within Colombia. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/10/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '7',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'CARTAGENA, CARTAGENA, Colombia'},
                 'demographics': {'ageRange': {'start': 85.0, 'end': 85.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/02/2020Z', 'end': '03/02/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/17/2020Z', 'end': '03/17/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESTADOS UNIDOS. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/08/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '8',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'BOGOTA, BOGOTA, Colombia'},
                 'demographics': {'ageRange': {'start': 22.0, 'end': 22.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/06/2020Z', 'end': '03/06/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/21/2020Z', 'end': '03/21/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESPAÑA. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/09/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '9',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'BOGOTA, BOGOTA, Colombia'},
                 'demographics': {'ageRange': {'start': 28.0, 'end': 28.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/11/2020Z', 'end': '03/11/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/07/2020Z', 'end': '03/07/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/23/2020Z', 'end': '03/23/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESPAÑA. \nDate reported online was 03/11/2020. \nDate reported to SIVIGILA was 03/08/2020. \nPatient recovery was confirmed by a negative PCR test.'},
                {'caseReference': {'sourceId': 'place_holder_ID',
                                   'sourceEntryId': '10',
                                   'sourceUrl': 'place_holder_URL'},
                 'location': {'query': 'BOGOTA, BOGOTA, Colombia'},
                 'demographics': {'ageRange': {'start': 36.0, 'end': 36.0},
                                  'gender': 'Female',
                                  'ethnicity': 'Other'},
                 'events': [{'name': 'confirmed',
                             'dateRange': {'start': '03/12/2020Z', 'end': '03/12/2020Z'}},
                            {'name': 'onsetSymptoms',
                             'dateRange': {'start': '03/06/2020Z', 'end': '03/06/2020Z'}},
                            {'name': 'outcome',
                             'value': 'Recovered',
                             'dateRange': {'start': '03/21/2020Z', 'end': '03/21/2020Z'}}],
                 'symptoms': {'status': 'Symptomatic', 'values': ['Mild']},
                 'notes': 'Patient self-isolated and recovered at home. \nCase is reported as importing the disease into Colombia, and country of origin is ESPAÑA. \nDate reported online was 03/12/2020. \nDate reported to SIVIGILA was 03/12/2020. \nPatient recovery was confirmed by a negative PCR test.'}])
