name: API tests (Python)

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/api-python-tests.yml'
    - 'api/python/**'
  pull_request:
    paths:
    - '.github/workflows/api-python-tests.yml'
    - 'api/python/**'
  workflow_dispatch:
    paths:
    - '.github/workflows/api-python-tests.yml'
    - 'api/python/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/python
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest
