name: API tests (Python)

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/api-python-tests.yml'
    - 'api/python/**'
  pull_request:
    paths:
    - '.github/workflows/api-python-tests.yml'
    - 'api/python/**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: api/python
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest
