name: Update case data

on:
  push:
    branches: [master]
    paths: ["/data-serving/scripts/convert-data/**"]

jobs:
  update-case-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MongoDB CLIs
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org=4.2.6 mongodb-org-server=4.2.6 mongodb-org-shell=4.2.6 mongodb-org-mongos=4.2.6 mongodb-org-tools=4.2.6 libcurl3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: python -m pip install --upgrade pandas

      - name: Run update script
        run: ./data-serving/scripts/data-pipeline/run_pipeline.sh -r .1 -m mongodb+srv://khmoran:P07EMKHI6Hk5kbhi@covid19-map-cluster01-sc7u9.mongodb.net
