name: Update case data

on:
  push:
    # Update the data when the conversion script changes.
    branches: [master]
    paths: ["/data-serving/scripts/convert-data/**"]
  repository_dispatch:
    # Update the data on a signal that the input data has changed.
    types: [latest-data-push]
  schedule:
    # TODO: Remove this once we've verified that repository_dispatch is working.
    # Every day at 5AM UTC (data is typically pushed a little after 4AM UTC).
    - cron: "0 5 * * *"

jobs:
  update-case-data-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install MongoDB CLIs
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA 656408E390CFB1F5
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades mongodb-org=4.2.6 mongodb-org-server=4.2.6 mongodb-org-shell=4.2.6 mongodb-org-mongos=4.2.6 mongodb-org-tools=4.2.6 libcurl3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: python -m pip install --upgrade pandas

      - name: Run update script
        run: ./data-serving/scripts/data-pipeline/convert_and_import_latest_data.sh -m ${{ secrets.DB_CONNECTION_URL }}
