name: Completeness

on:
  schedule:
    - cron: "5 5 * * SUN"

jobs:
  freshness:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ingestion/monitoring
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements-completeness.txt
    - name: Upload completeness
      run: python completeness.py
