# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Curator API Node.js CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/curator-api-node.yml"
      - "verification/curator-service/api/**"
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/curator-api-node.yml"
      - "verification/curator-service/api/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Build and test
        run: |
          npm ci
          npm run build
          npm test
        working-directory: verification/curator-service/api
        env:
          CI: true
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          file: verification/curator-service/api/coverage/coverage-final.json
