name: Export tests

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/export-tests.yml'
    - 'data-serving/scripts/export-data/*.py'
    - 'data-serving/scripts/export-data/*.sh'
  pull_request:
    paths:
    - '.github/workflows/export-tests.yml'
    - 'data-serving/scripts/export-data/*.py'
    - 'data-serving/scripts/export-data/*.sh'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: data-serving/scripts/export-data
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Lint with shellcheck
      run: |
        shellcheck *.sh
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        pip install pytest
        pytest
