name: Ingestion functions deploy

on:
  push:
    branches: [main, '*-stable']
    paths:
    - '.github/workflows/ingestion-functions-deploy.yml'
    - 'ingestion/functions/**'
    - '!ingestion/functions/README.md'
    # Build whenever a new tag is created.
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR (latest)
      if: ${{ github.ref == 'refs/heads/main' }}
      working-directory: ingestion/functions
      env:
        NOTIFY_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_METRICS_URL }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gdh-ingestor
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg NOTIFY_WEBHOOK_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Build, tag, and push image to Amazon ECR (stable)
      if: ${{ endsWith(github.ref, '-stable') }}
      working-directory: ingestion/functions
      env:
        NOTIFY_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_METRICS_URL }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gdh-ingestor
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --build-arg NOTIFY_WEBHOOK_URL -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:stable .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:stable
