name: Ingestion functions AWS SAM build

on:
  pull_request:
    paths:
    - '.github/workflows/ingestion-aws-sam-build.yml'
    - 'ingestion/functions/**'

jobs:
  sam-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ingestion/functions
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: sam build
      run: sam build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
