name: Prune uploads (dev)

on:
  schedule:
    - cron: "4 4 * * *"

jobs:
  prune:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-serving/scripts/prune-uploads
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Prune uploads
      env:
        EPOCH: 2021-07-30
        CONN: ${{ secrets.DB_CONNECTION_URL_DEV }}
      run: python prune_uploads.py
