name: Prune uploads

on:
  schedule:
    - cron: "9 5,17 * * *"

jobs:
  prune:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-serving/scripts/prune-uploads
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Prune uploads
      env:
        PRUNE_EPOCH: 2021-07-30
        CONN: ${{ secrets.DB_CONNECTION_URL_PROD }}
        PRUNE_UPLOADS_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_METRICS_URL }}
      run: python prune_uploads.py --run-hooks=all
