name: Prune uploads script tests

on:
  push:
    branches: [main]
    paths:
    - '.github/workflows/prune-uploads-tests.yml'
    - 'data-serving/scripts/prune-uploads/**'
    - '!data-serving/scripts/prune-uploads/README.md'
  pull_request:
    paths:
    - '.github/workflows/prune-uploads-tests.yml'
    - 'data-serving/scripts/prune-uploads/**'
    - '!data-serving/scripts/prune-uploads/README.md'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: data-serving/scripts/prune-uploads
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest
