name: Update dev curator-service database schema

on:
  push:
    # Run workflow when the schema changes.
    branches: [main]
    paths:
      - "verification/curator-service/api/src/schemas/**"
      - ".github/workflows/update-dev-curator-db-schema.yaml"

jobs:
  update-sources-data-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      
      - name: Update dev sources schema
        env:
          CONN: ${{ secrets.DB_CONNECTION_URL_DEV }}
          DB: "covid19"
          COLL: "sources"
          # Those are relative to the setup-db directory, not the working dir.
          SCHEMA: "../../../verification/curator-service/api/src/schemas/sources.schema.json"
          INDEXES: "../../../verification/curator-service/api/src/schemas/sources.indexes.json"
        run: npm --prefix data-serving/scripts/setup-db run setup