name: Update dev data-service database schema

on:
  push:
    # Run workflow when the schema changes.
    branches: [main]
    paths:
      - "data-serving/scripts/setup-db/schemas/**"
      - ".github/workflows/update-dev-data-db-schema.yaml"

jobs:
  update-case-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Update dev cases schema
        env:
          CONN: ${{ secrets.DB_CONNECTION_URL_DEV }}
          DB: "covid19"
          COLL: "cases"
          # Those are relative to the setup-db directory, not the working dir.
          SCHEMA: "./schemas/cases.schema.json"
          INDEXES: "./schemas/cases.indexes.json"
        run: npm --prefix data-serving/scripts/setup-db run setup
