import os
import unittest
from peru import peru

_SOURCE_ID = "placeholder_ID"
_SOURCE_URL = "placeholder_URL"


class PeruTest(unittest.TestCase):
    def setUp(self):
        self.maxDiff = 5000

    def test_parse(self):
        '''
        Includes a row where province and district are unspecified, where it should return just
        the department and country
        '''
        current_dir = os.path.dirname(__file__)
        sample_data_file = os.path.join(current_dir, "sample_data.csv")

        result = peru.parse_cases(sample_data_file, _SOURCE_ID, _SOURCE_URL)
        self.assertCountEqual(list(result),
                              [{'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '7320cabdc1aaca6c59014cae76a134e6',
                                                  'sourceUrl': 'placeholder_URL'},
                                'location': {'administrativeAreaLevel3': 'FERREÑAFE',
                                             'administrativeAreaLevel2': 'FERREÑAFE',
                                             'administrativeAreaLevel1': 'LAMBAYEQUE',
                                             'geoResolution': 'Admin3',
                                             'name': 'FERREÑAFE, FERREÑAFE, LAMBAYEQUE, Peru',
                                             'geometry': {'latitude': -6.62052434308725,
                                                          'longitude': -79.7911185840526}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/29/2020Z', 'end': '03/29/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 35.0, 'end': 35.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': 'cecdbf10074dbc011ae05b3cbd320a6f',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'CHORRILLOS',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'CHORRILLOS, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.1926451966803,
                                                            'longitude': -77.0058884465196}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 36.0, 'end': 36.0},
                                                   'gender': 'Male'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '71ecb6bccb248b0bb2ac72ed51b5e979',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 1.0, 'end': 1.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '566af4276cbe9359abe93f9aa86396c3',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 65.0, 'end': 65.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '027561e9d126e7c283d79c02cede562d',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 32.0, 'end': 32.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': 'f016889b9ba5bd95cf15d60205cbd82e',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 44.0, 'end': 44.0},
                                                   'gender': 'Male'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '971f8e1295583756d81fe42f3318488c',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 29.0, 'end': 29.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': 'bc45b71b005a96f32eeb97060616a999',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 44.0, 'end': 44.0},
                                                   'gender': 'Female'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '0e2a1928ddd07d99978758e86b034131',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel1': 'LIMA',
                                               'name': 'LIMA, Peru',
                                               'geoResolution': 'Admin1',
                                               'geometry': {'latitude': -11.7855675478949,
                                                            'longitude': -76.6271728665078}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 41.0, 'end': 41.0},
                                                   'gender': 'Male'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '1caabc6f4c64b5910bd8254fa0f949ce',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'EL AGUSTINO',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'EL AGUSTINO, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0400969138003,
                                                            'longitude': -76.9874046804472}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'Serological test',
                                              'dateRange': {'start': '03/30/2020Z', 'end': '03/30/2020Z'}}],
                                  'demographics': {'ageRange': {'start': 40.0, 'end': 40.0},
                                                   'gender': 'Male'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': '028942f0d49b634ff00563c766ea5129',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '01/05/2021Z', 'end': '01/05/2021Z'}}],
                                  'demographics': {'gender': 'Male'}},
                               {'caseReference': {'sourceId': 'placeholder_ID',
                                                  'sourceEntryId': 'ca700e98a91c6f267e0cb69d9a32ef91',
                                                  'sourceUrl': 'placeholder_URL'},
                                  'location': {'administrativeAreaLevel3': 'LIMA',
                                               'administrativeAreaLevel2': 'LIMA',
                                               'administrativeAreaLevel1': 'LIMA',
                                               'geoResolution': 'Admin3',
                                               'name': 'LIMA, LIMA, LIMA, Peru',
                                               'geometry': {'latitude': -12.0510318836147,
                                                            'longitude': -77.0488741340857}},
                                  'events': [{'name': 'confirmed',
                                              'value': 'PCR test',
                                              'dateRange': {'start': '01/19/2021Z', 'end': '01/19/2021Z'}}],
                                  'demographics': {'gender': 'Male'}}])
